name: graphview
description:  GraphView is used to display data in graph structures. It can display tree layout using BuchheimWalkerAlgorithm and Directed graph using FruchtermanReingoldAlgorithm. Useful for Family Tree, Hierarchy View, Flutter Widget Tree.Useful for Social network, Mind Map, Cluster, Graphs, Intercity Road Network,
version: 0.1.0
homepage: https://github.com/nabil6391/graphview

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  pedantic: ^1.9.0
  flutter:
    sdk: flutter

flutter:
