name: graphview
description:  GraphView is used to display data in graph structures. It can display Tree layout and Directed graph. Useful for Family Tree, Hierarchy View.
version: 0.1.2
homepage: https://github.com/nabil6391/graphview

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  pedantic: ^1.9.2
  flutter:
    sdk: flutter

flutter:
